# Generated by Django 3.2 on 2024-11-07 20:48

import django.contrib.auth.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя (максимум 150 символов).', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.models.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
