# Generated by Django 3.2 on 2024-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя (максимум 150 символов).', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
