# Generated by Django 3.2 on 2024-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Напишите информацию о себе', verbose_name='Биография пользователя'),
        ),
    ]
